name: Deploy Cloud Functions (production)
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: rss-delivery-deploy-prod

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  prepare:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      function_name: ${{ steps.set_name.outputs.function_name }}
    steps:
      - name: Set function name
        id: set_name
        run: |
          # if [ -n "${{ github.event.pull_request.number }}" ]; then
          #   echo "function_name=rss-delivery${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          # else
            echo "function_name=rss-delivery" >> $GITHUB_OUTPUT
          # fi

  deploy:
    needs: prepare
    uses: yananob/cloud-functions-common/.github/workflows/deploy-cloud-functions.yaml@main
    with:
      function_name: ${{ needs.prepare.outputs.function_name }}
      service_account_name: 'cloud-run-functions-deployer'
      wip_pool_name: 'github-actions-pool'
      wip_provider_name: 'github-provider'
      runtime: php82
      secrets_config: |-
        FIREBASE_SERVICE_ACCOUNT
        LINE_TOKENS_N_TARGETS
        RAINDROP_KEY
      deploy_http_trigger: true
      deploy_event_trigger: true
      http_max_instance_count: 1
      memory: '256M'
      http_timeout: '5m'
      event_timeout: '540s'
      environment_variables: |-
        APP_ENV=production
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}

  comment:
    needs: [prepare, deploy]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    permissions:
      pull-requests: write
      contents: read  # チェックアウトなど、他の操作に必要
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Add comment to PR
        run: |
          gh pr comment $PR_NUMBER --body "Deployed to url https://${{ secrets.GCP_REGION }}-${{ secrets.GCP_PROJECT_ID }}.cloudfunctions.net/${{ needs.prepare.outputs.function_name }}"
