name: Deploy Cloud Functions (production)
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: rss-delivery-deploy-prod

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    uses: yananob/cloud-functions-common/.github/workflows/deploy-cloud-functions.yaml@main
    with:
      function_name: 'rss-delivery'
      # project_id: 'nobu5-393106'
      # region: 'us-west1'
      service_account_name: 'cloud-run-functions-deployer'
      # gcp_project_number: '1035100650942'
      wip_pool_name: 'github-actions-pool'
      wip_provider_name: 'github-provider'
      # secrets_project_id: 'nobu5-393106'
      secrets_config: |-
        FIREBASE_SERVICE_ACCOUNT
        LINE_TOKENS_N_TARGETS
        RAINDROP_KEY
      deploy_http_trigger: true
      deploy_event_trigger: true
      http_max_instance_count: 1
      memory: '256M'
      http_timeout: '5m'
      event_timeout: '5m'
      environment_variables: |-
        APP_ENV=production
