name: Deploy Cloud Functions (test)
on:
  push:
    branches:
      - test
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'edited'
      - 'reopened'
  workflow_dispatch:

concurrency:
  group: rss-delivery-deploy-test

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    uses: yananob/cloud-functions-common/.github/workflows/deploy-cloud-functions.yaml@main
    with:
      function_name: 'rss-delivery-test'
      project_id: 'nobu5-393106'
      region: 'us-west1'
      service_account_name: 'cloud-run-functions-deployer'
      gcp_project_number: '1035100650942'
      wip_pool_name: 'github-actions-pool'
      wip_provider_name: 'github-provider'
      secrets_project_id: 'nobu5-393106'
      secrets_config: |-
        FIREBASE_SERVICE_ACCOUNT
        LINE_TOKENS_N_TARGETS
        RAINDROP_KEY
      deploy_http_trigger: false
      deploy_event_trigger: true
      http_max_instance_count: 1
      memory: '256M'
      http_timeout: '5m'
      event_timeout: '5m'
